# Generated by Django 2.2.1 on 2019-06-10 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DomiCarg', models.CharField(default='', max_length=1, verbose_name='Dominio')),
                ('ClasCarg', models.CharField(default='', max_length=2, verbose_name='Clase')),
                ('OrdeCarg', models.CharField(default='', max_length=3, verbose_name='Orden')),
                ('GeneCarg', models.CharField(default='', max_length=4, verbose_name='Genero')),
                ('NombCarg', models.CharField(default='', max_length=250, verbose_name='Nombre')),
                ('EsCargo', models.CharField(default='', max_length=20, verbose_name='Es cargo')),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Empleos y Cargos',
            },
        ),
        migrations.AlterModelOptions(
            name='estacivil',
            options={'verbose_name': 'Estado civil', 'verbose_name_plural': 'Estados civiles'},
        ),
        migrations.AlterModelOptions(
            name='etnia',
            options={'verbose_name': 'Etnia', 'verbose_name_plural': 'Etnias'},
        ),
        migrations.AlterModelOptions(
            name='tipodocu',
            options={'verbose_name': 'Tipo de documento', 'verbose_name_plural': 'Tipos de documento'},
        ),
        migrations.AlterModelOptions(
            name='tipoestu',
            options={'verbose_name': 'Tipos de educacion', 'verbose_name_plural': 'Tipos de educaciones'},
        ),
        migrations.AlterModelOptions(
            name='tipologr',
            options={'verbose_name': 'Tipo de logro', 'verbose_name_plural': 'Tipos de logros'},
        ),
        migrations.AlterField(
            model_name='estacivil',
            name='NombEsCi',
            field=models.CharField(default='', max_length=50, verbose_name='Nombre estado civil'),
        ),
        migrations.AlterField(
            model_name='etnia',
            name='NombEtni',
            field=models.CharField(default='', max_length=50, verbose_name='Nombre Etnia'),
        ),
        migrations.AlterField(
            model_name='tipodocu',
            name='NombTiDo',
            field=models.CharField(default='', max_length=50, verbose_name='Nombre tipo de documento'),
        ),
        migrations.AlterField(
            model_name='tipoestu',
            name='NombTiEs',
            field=models.CharField(default='', max_length=50, verbose_name='Nombre tipo de educacion'),
        ),
        migrations.AlterField(
            model_name='tipologr',
            name='NombTiLo',
            field=models.CharField(default='', max_length=50, verbose_name='Nombre tipo de logro'),
        ),
    ]
