# Generated by Django 2.2.2 on 2019-06-10 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DomiCargo', models.CharField(default='', max_length=1, verbose_name='DOMINIO')),
                ('ClasCargo', models.CharField(default='', max_length=2, verbose_name='CLASE')),
                ('OrdeCargo', models.CharField(default='', max_length=3, verbose_name='ORDEN')),
                ('GeneCargo', models.CharField(default='', max_length=4, verbose_name='GENERO')),
                ('NomCargo', models.CharField(default='', max_length=250, verbose_name='NOMBRE')),
                ('EsCargo', models.CharField(default='', max_length=20, verbose_name='ES CARGO')),
            ],
            options={
                'verbose_name': 'Cargos',
                'verbose_name_plural': 'Empleos y Cargos',
            },
        ),
    ]
