# Generated by Django 2.2.2 on 2019-06-10 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0002_cargos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estacivil',
            options={'verbose_name': 'EstadoCivil', 'verbose_name_plural': 'EstadosCiviles'},
        ),
        migrations.AlterModelOptions(
            name='etnia',
            options={'verbose_name': 'Etnia', 'verbose_name_plural': 'Etnias'},
        ),
        migrations.AlterModelOptions(
            name='tipodocu',
            options={'verbose_name': 'TipoDocumento', 'verbose_name_plural': 'TipoDocumentos'},
        ),
        migrations.AlterModelOptions(
            name='tipoestu',
            options={'verbose_name': 'TipoEstudio', 'verbose_name_plural': 'TipoEstudios'},
        ),
        migrations.AlterModelOptions(
            name='tipologr',
            options={'verbose_name': 'Cargos', 'verbose_name_plural': 'Empleos y Cargos'},
        ),
    ]
