# Generated by Django 2.2.1 on 2019-06-11 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainuser', '0003_auto_20190610_1940'),
        ('parametros', '0003_auto_20190610_1546'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TipoCargo',
        ),
    ]
