# Generated by Django 2.2.2 on 2019-06-10 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0003_auto_20190610_0849'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipologr',
            options={'verbose_name': 'TipoLogro', 'verbose_name_plural': 'TipoLogros'},
        ),
    ]
