# Generated by Django 2.2.2 on 2019-06-10 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0004_auto_20190610_0849'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idLogros', models.IntegerField(verbose_name='idLogros')),
                ('idTipoLogr', models.IntegerField(verbose_name='idTipoLogro')),
                ('idTipoUsua', models.IntegerField()),
                ('FechLogr', models.DateField(auto_now=True, verbose_name='')),
                ('NombrLogr', models.CharField(default='', max_length=255, verbose_name='Nombre')),
                ('DescLogr', models.TextField(verbose_name='Descripción')),
            ],
        ),
    ]
