# Generated by Django 2.2.2 on 2019-06-10 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0005_logros'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logros',
            options={'verbose_name': 'Logro', 'verbose_name_plural': 'Logros'},
        ),
        migrations.AlterField(
            model_name='logros',
            name='DescLogr',
            field=models.TextField(verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='logros',
            name='FechLogr',
            field=models.DateField(verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='logros',
            name='idTipoLogr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametros.TipoLogr', verbose_name='idTipoLogro'),
        ),
    ]
