# Generated by Django 2.1.8 on 2019-06-25 23:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('IdUsuarios', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id usuario')),
                ('Titulo', models.CharField(default='', max_length=100, verbose_name='Título')),
                ('Ocup', models.CharField(default='', max_length=100, verbose_name='Ocupación')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfiles',
            },
        ),
    ]
