# Generated by Django 2.1.8 on 2019-06-25 23:26

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parametros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatosUsua',
            fields=[
                ('IdUsuarios', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id usuario')),
                ('IdPaises', models.IntegerField(verbose_name='Pais')),
                ('IdDepartamentos', models.IntegerField(verbose_name='Departamento')),
                ('IdCiudades', models.IntegerField(verbose_name='Ciudad')),
                ('foto', models.FileField(default='foto.jpg', max_length=500, upload_to='fotos/', verbose_name='Foto del usuario')),
                ('PerfilPro', ckeditor.fields.RichTextField(default='', max_length=200, verbose_name='Perfil profesional')),
                ('Genero', models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], max_length=15)),
                ('Telefono', models.CharField(default='', max_length=50, verbose_name='Telefono')),
                ('Direccion', models.CharField(default='', max_length=100, verbose_name='Direccion')),
                ('IdEstaCivil', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='parametros.EstaCivil', verbose_name='Estado civil')),
                ('IdEtnias', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='parametros.Etnia', verbose_name='Etnia')),
                ('IdTipoDocu', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='parametros.TipoDocu', verbose_name='Tipo de documento')),
            ],
            options={
                'verbose_name': 'Datos de usuario',
                'verbose_name_plural': 'Datos de usuarios',
            },
        ),
        migrations.CreateModel(
            name='Educacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IdUsuarios', models.IntegerField(verbose_name='Id usuario')),
                ('IdPaises', models.IntegerField(verbose_name='País')),
                ('IdDepartamentos', models.IntegerField(verbose_name='Departamento')),
                ('IdCiudades', models.IntegerField(verbose_name='Ciudad')),
                ('Instituto', models.CharField(default='', max_length=255, verbose_name='Instituto')),
                ('Titulo', models.CharField(default='', max_length=255, verbose_name='Titulo')),
                ('FechGrado', models.DateField(verbose_name='Fecha de grado')),
                ('IdTipoEstu', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='parametros.TipoEstu', verbose_name='Tipo de educación')),
            ],
            options={
                'verbose_name': 'Educación',
                'verbose_name_plural': 'Educaciones',
            },
        ),
        migrations.CreateModel(
            name='Experiencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IdUsuarios', models.IntegerField(verbose_name='Id usuario')),
                ('IdPaises', models.IntegerField(verbose_name='Pais')),
                ('IdDepartamentos', models.IntegerField(verbose_name='Departamento')),
                ('IdCiudades', models.IntegerField(verbose_name='Ciudad')),
                ('Empresa', models.CharField(default='', max_length=250, verbose_name='Empresa')),
                ('FechaIni', models.DateField(verbose_name='Fecha de inicio')),
                ('FechaFin', models.DateField(verbose_name='Fecha de finalizacion')),
                ('Funciones', models.CharField(default='', max_length=500, verbose_name='Funcion')),
                ('Logros', ckeditor.fields.RichTextField(default='', max_length=500, verbose_name='Logros')),
                ('IdCargos', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='parametros.Cargo', verbose_name='Cargo')),
            ],
            options={
                'verbose_name': 'Experiencia',
                'verbose_name_plural': 'Experiencias',
            },
        ),
        migrations.CreateModel(
            name='Habilidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IdUsuarios', models.IntegerField(verbose_name='Id Usuario')),
                ('NombHabil', models.CharField(default='', max_length=155, verbose_name='Nombre Habilidad')),
                ('NiveHabil', models.CharField(choices=[('Avanzado', 'Avanzado'), ('Intermedio', 'Intermedio'), ('Básico', 'Básico')], default='', max_length=50, verbose_name='Nivel Habilidad')),
            ],
            options={
                'verbose_name': 'Habilidad',
                'verbose_name_plural': 'Habilidades',
            },
        ),
        migrations.CreateModel(
            name='Logro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IdUsuarios', models.IntegerField(verbose_name='Id usuario')),
                ('FechLogr', models.DateField(verbose_name='Fecha')),
                ('NombrLogr', models.CharField(default='', max_length=255, verbose_name='Nombre logro')),
                ('DescLogr', ckeditor.fields.RichTextField(default='', max_length=200, verbose_name='Descripcion')),
                ('idTipoLogr', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='parametros.TipoLogr', verbose_name='Id tipo de logro')),
            ],
            options={
                'verbose_name': 'Logro',
                'verbose_name_plural': 'Logros',
            },
        ),
    ]
