# Generated by Django 2.2.1 on 2019-06-04 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IdUsuarios', models.IntegerField()),
                ('IdTipoUsua', models.IntegerField()),
                ('NombUsua', models.CharField(max_length=50)),
                ('ApellUsua', models.CharField(max_length=50)),
                ('EmailUsua', models.CharField(max_length=50)),
                ('EstaUsua', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Usuarios',
        ),
    ]
