# Generated by Django 2.1.8 on 2019-06-25 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DomiCarg', models.CharField(default='', max_length=1, verbose_name='Dominio')),
                ('ClasCarg', models.CharField(default='', max_length=2, verbose_name='Clase')),
                ('OrdeCarg', models.CharField(default='', max_length=3, verbose_name='Orden')),
                ('GeneCarg', models.CharField(default='', max_length=4, verbose_name='Genero')),
                ('NombCarg', models.CharField(default='', max_length=250, verbose_name='Nombre')),
                ('EsCargo', models.CharField(default='', max_length=20, verbose_name='Es cargo')),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Empleos y Cargos',
            },
        ),
        migrations.CreateModel(
            name='EstaCivil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombEsCi', models.CharField(default='', max_length=50, verbose_name='Nombre estado civil')),
            ],
            options={
                'verbose_name': 'Estado civil',
                'verbose_name_plural': 'Estados civiles',
            },
        ),
        migrations.CreateModel(
            name='Etnia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombEtni', models.CharField(default='', max_length=50, verbose_name='Nombre Etnia')),
            ],
            options={
                'verbose_name': 'Etnia',
                'verbose_name_plural': 'Etnias',
            },
        ),
        migrations.CreateModel(
            name='TipoDocu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombTiDo', models.CharField(default='', max_length=50, verbose_name='Nombre tipo de documento')),
            ],
            options={
                'verbose_name': 'Tipo de documento',
                'verbose_name_plural': 'Tipos de documento',
            },
        ),
        migrations.CreateModel(
            name='TipoEstu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombTiEs', models.CharField(default='', max_length=50, verbose_name='Nombre tipo de educacion')),
            ],
            options={
                'verbose_name': 'Tipos de educacion',
                'verbose_name_plural': 'Tipos de educaciones',
            },
        ),
        migrations.CreateModel(
            name='TipoLogr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombTiLo', models.CharField(default='', max_length=50, verbose_name='Nombre tipo de logro')),
            ],
            options={
                'verbose_name': 'Tipo de logro',
                'verbose_name_plural': 'Tipos de logros',
            },
        ),
    ]
