# Generated by Django 2.1.8 on 2019-07-01 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainuser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosusua',
            name='IdUsuarios',
            field=models.CharField(max_length=11, primary_key=True, serialize=False, verbose_name='Id usuario'),
        ),
        migrations.AlterField(
            model_name='educacion',
            name='IdUsuarios',
            field=models.CharField(max_length=11, verbose_name='Id usuario'),
        ),
        migrations.AlterField(
            model_name='experiencia',
            name='IdUsuarios',
            field=models.CharField(max_length=11, verbose_name='Id usuario'),
        ),
        migrations.AlterField(
            model_name='habilidad',
            name='IdUsuarios',
            field=models.CharField(max_length=11, verbose_name='Id Usuario'),
        ),
        migrations.AlterField(
            model_name='logro',
            name='IdUsuarios',
            field=models.CharField(max_length=11, verbose_name='Id usuario'),
        ),
    ]
