# Generated by Django 2.1.8 on 2019-07-01 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainuser', '0002_auto_20190701_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosusua',
            name='Genero',
            field=models.CharField(choices=[('Default', 'Seleccione su genero'), ('Masculino', 'Masculino'), ('Femenino', 'Femenino')], max_length=15),
        ),
    ]
