# Generated by Django 2.2.1 on 2019-06-10 20:13

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parametros', '0002_auto_20190610_1513'),
    ]

    operations = [
        migrations.CreateModel(
            name='Educacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IdEducacion', models.IntegerField(verbose_name='Id educacion')),
                ('IdEdus', models.IntegerField(verbose_name='Id tipo educación')),
                ('IdUsuarios', models.IntegerField(verbose_name='Id usuario')),
                ('IdTipoUsua', models.IntegerField(verbose_name='Id tipo usuario')),
                ('IdCiudades', models.IntegerField(verbose_name='Id ciudades')),
                ('IdDepartamentos', models.IntegerField(verbose_name='Id departamentos')),
                ('IdPaises', models.IntegerField(verbose_name='Id paises')),
                ('Instituto', models.CharField(default='', max_length=255, verbose_name='Instituto')),
                ('Titulo', models.CharField(default='', max_length=255, verbose_name='Titulo')),
                ('FechGrado', models.DateTimeField(verbose_name='Fecha de grado')),
            ],
            options={
                'verbose_name': 'Educacion',
                'verbose_name_plural': 'Educaciones',
            },
        ),
        migrations.CreateModel(
            name='Experiencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IdExperiencia', models.IntegerField(verbose_name='EXPERIENCIA')),
                ('IdUsuarios', models.IntegerField(verbose_name='USUARIOS')),
                ('IdTipoUsua', models.IntegerField(verbose_name='TIPOUSUARIO')),
                ('IdCargos', models.IntegerField(verbose_name='CARGOS')),
                ('IdTipoCarg', models.IntegerField(verbose_name='TIPOCARGO')),
                ('IdCiudades', models.IntegerField(verbose_name='CIUDADES')),
                ('IdDepartamentos', models.IntegerField(verbose_name='DEPARTAMENTOS')),
                ('IdPaises', models.IntegerField(verbose_name='PAISES')),
                ('Empresa', models.CharField(default='', max_length=250, verbose_name='EMPRESA')),
                ('FechaIni', models.DateTimeField(auto_now=True, verbose_name='FECHAINICIO')),
                ('FechaFin', models.DateTimeField(auto_now=True, verbose_name='FECHAFINAL')),
                ('Funciones', models.CharField(default='', max_length=500, verbose_name='FUNCION')),
                ('Logros', models.CharField(default='', max_length=500, verbose_name='LOGRO')),
            ],
            options={
                'verbose_name': 'Experiencia',
                'verbose_name_plural': 'Experiencias',
            },
        ),
        migrations.CreateModel(
            name='Habilidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IdHabilidades', models.IntegerField(verbose_name='Id Habilidades')),
                ('IdUsuarios', models.IntegerField(verbose_name='Id Usuario')),
                ('IdTipoUsua', models.IntegerField(verbose_name='Id Tipo Usuario')),
                ('NombHabil', models.CharField(default='', max_length=155, verbose_name='Nombre Habilidad')),
                ('NiveHabil', models.CharField(default='', max_length=155, verbose_name='Nivel Habilidad')),
            ],
            options={
                'verbose_name': 'Habilidad',
                'verbose_name_plural': 'Habilidades',
            },
        ),
        migrations.CreateModel(
            name='Logro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idLogros', models.IntegerField(verbose_name='Id Logros')),
                ('FechLogr', models.DateField(verbose_name='Fecha')),
                ('NombrLogr', models.CharField(default='', max_length=255, verbose_name='Nombre logro')),
                ('DescLogr', models.TextField(verbose_name='Descripcion')),
                ('idTipoLogr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametros.TipoLogr', verbose_name='Id tipo de logro')),
            ],
            options={
                'verbose_name': 'Logro',
                'verbose_name_plural': 'Logros',
            },
        ),
        migrations.CreateModel(
            name='DatosUsua',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IdUsuarios', models.IntegerField(verbose_name='Id usuario')),
                ('IdCiudades', models.IntegerField()),
                ('IdDepartamentos', models.IntegerField()),
                ('IdPaises', models.IntegerField()),
                ('PerfilPro', ckeditor.fields.RichTextField(max_length=200, verbose_name='Perfil profesional')),
                ('Genero', models.CharField(max_length=50)),
                ('Telefono', models.CharField(max_length=50, verbose_name='Telefono')),
                ('Direccion', models.CharField(max_length=100, verbose_name='Direccion')),
                ('IdEstaCivil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametros.EstaCivil', verbose_name='Estado civil')),
                ('IdEtnias', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametros.Etnia', verbose_name='Etnia')),
                ('IdTipoDocu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametros.TipoDocu', verbose_name='Tipo de documento')),
            ],
            options={
                'verbose_name': 'Datos de usuario',
                'verbose_name_plural': 'Datos de usuarios',
            },
        ),
    ]
