# Generated by Django 2.2.1 on 2019-06-10 20:46

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0003_auto_20190610_1546'),
        ('mainuser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DomiCarg', models.CharField(default='', max_length=1, verbose_name='Dominio')),
                ('ClasCarg', models.CharField(default='', max_length=2, verbose_name='Clase')),
                ('OrdeCarg', models.CharField(default='', max_length=3, verbose_name='Orden')),
                ('GeneCarg', models.CharField(default='', max_length=4, verbose_name='Genero')),
                ('NombCarg', models.CharField(default='', max_length=250, verbose_name='Nombre')),
                ('EsCargo', models.CharField(default='', max_length=20, verbose_name='Es cargo')),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Empleos y Cargos',
            },
        ),
        migrations.AlterModelOptions(
            name='educacion',
            options={'verbose_name': 'Educación', 'verbose_name_plural': 'Educaciones'},
        ),
        migrations.RemoveField(
            model_name='educacion',
            name='IdEdus',
        ),
        migrations.RemoveField(
            model_name='educacion',
            name='IdTipoUsua',
        ),
        migrations.RemoveField(
            model_name='experiencia',
            name='IdTipoUsua',
        ),
        migrations.RemoveField(
            model_name='habilidad',
            name='IdTipoUsua',
        ),
        migrations.AddField(
            model_name='educacion',
            name='IdTipoEstu',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='parametros.TipoEstu', verbose_name='Tipo de educación'),
        ),
        migrations.AlterField(
            model_name='datosusua',
            name='Direccion',
            field=models.CharField(default='', max_length=100, verbose_name='Direccion'),
        ),
        migrations.AlterField(
            model_name='datosusua',
            name='Genero',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='datosusua',
            name='IdCiudades',
            field=models.IntegerField(verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='datosusua',
            name='IdDepartamentos',
            field=models.IntegerField(verbose_name='Departamento'),
        ),
        migrations.AlterField(
            model_name='datosusua',
            name='IdEstaCivil',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='parametros.EstaCivil', verbose_name='Estado civil'),
        ),
        migrations.AlterField(
            model_name='datosusua',
            name='IdEtnias',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='parametros.Etnia', verbose_name='Etnia'),
        ),
        migrations.AlterField(
            model_name='datosusua',
            name='IdPaises',
            field=models.IntegerField(verbose_name='Pais'),
        ),
        migrations.AlterField(
            model_name='datosusua',
            name='IdTipoDocu',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='parametros.TipoDocu', verbose_name='Tipo de documento'),
        ),
        migrations.AlterField(
            model_name='datosusua',
            name='PerfilPro',
            field=ckeditor.fields.RichTextField(default='', max_length=200, verbose_name='Perfil profesional'),
        ),
        migrations.AlterField(
            model_name='datosusua',
            name='Telefono',
            field=models.CharField(default='', max_length=50, verbose_name='Telefono'),
        ),
        migrations.AlterField(
            model_name='educacion',
            name='IdCiudades',
            field=models.IntegerField(verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='educacion',
            name='IdDepartamentos',
            field=models.IntegerField(verbose_name='Departamento'),
        ),
        migrations.AlterField(
            model_name='educacion',
            name='IdEducacion',
            field=models.IntegerField(verbose_name='Id educación'),
        ),
        migrations.AlterField(
            model_name='educacion',
            name='IdPaises',
            field=models.IntegerField(verbose_name='País'),
        ),
        migrations.AlterField(
            model_name='experiencia',
            name='Empresa',
            field=models.CharField(default='', max_length=250, verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='experiencia',
            name='FechaFin',
            field=models.DateTimeField(verbose_name='Fecha de finalizacion'),
        ),
        migrations.AlterField(
            model_name='experiencia',
            name='FechaIni',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='experiencia',
            name='Funciones',
            field=models.CharField(default='', max_length=500, verbose_name='Funcion'),
        ),
        migrations.AlterField(
            model_name='experiencia',
            name='IdCargos',
            field=models.IntegerField(verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='experiencia',
            name='IdCiudades',
            field=models.IntegerField(verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='experiencia',
            name='IdDepartamentos',
            field=models.IntegerField(verbose_name='Departamento'),
        ),
        migrations.AlterField(
            model_name='experiencia',
            name='IdExperiencia',
            field=models.IntegerField(verbose_name='Id experiencia'),
        ),
        migrations.AlterField(
            model_name='experiencia',
            name='IdPaises',
            field=models.IntegerField(verbose_name='Pais'),
        ),
        migrations.AlterField(
            model_name='experiencia',
            name='IdTipoCarg',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='parametros.TipoCargo', verbose_name='Tipo de cargo'),
        ),
        migrations.AlterField(
            model_name='experiencia',
            name='IdUsuarios',
            field=models.IntegerField(verbose_name='Id usuario'),
        ),
        migrations.AlterField(
            model_name='experiencia',
            name='Logros',
            field=ckeditor.fields.RichTextField(default='', max_length=500, verbose_name='Logros'),
        ),
        migrations.AlterField(
            model_name='logro',
            name='DescLogr',
            field=models.TextField(default='', verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='logro',
            name='FechLogr',
            field=models.DateField(verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='logro',
            name='idLogros',
            field=models.IntegerField(verbose_name='Id Logros'),
        ),
        migrations.AlterField(
            model_name='logro',
            name='idTipoLogr',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='parametros.TipoLogr', verbose_name='Id tipo de logro'),
        ),
    ]
