# Generated by Django 2.2.1 on 2019-06-11 00:40

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainuser', '0002_auto_20190610_1546'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experiencia',
            name='IdTipoCarg',
        ),
        migrations.AlterField(
            model_name='logro',
            name='DescLogr',
            field=ckeditor.fields.RichTextField(default='', max_length=200, verbose_name='Descripcion'),
        ),
    ]
