# Generated by Django 2.2.1 on 2019-06-11 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainuser', '0003_auto_20190610_1940'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cargo',
        ),
    ]
