# Generated by Django 2.2.1 on 2019-06-11 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainuser', '0004_auto_20190610_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiencia',
            name='IdCargos',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='parametros.Cargo', verbose_name='Cargo'),
        ),
    ]
