# Generated by Django 2.2.1 on 2019-06-11 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainuser', '0005_auto_20190610_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosusua',
            name='foto',
            field=models.FileField(default='foto.jpg', max_length=500, upload_to='fotos/', verbose_name='Foto del usuario'),
        ),
    ]
