# Generated by Django 2.2.1 on 2019-06-11 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainuser', '0006_datosusua_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiencia',
            name='FechaFin',
            field=models.DateField(verbose_name='Fecha de finalizacion'),
        ),
        migrations.AlterField(
            model_name='experiencia',
            name='FechaIni',
            field=models.DateField(verbose_name='Fecha de inicio'),
        ),
    ]
