# Generated by Django 2.2.1 on 2019-06-16 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainuser', '0007_auto_20190611_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosusua',
            name='Genero',
            field=models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], max_length=15),
        ),
    ]
