# Generated by Django 2.2.1 on 2019-06-17 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainuser', '0008_auto_20190615_2337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habilidad',
            name='IdHabilidades',
        ),
    ]
